### ISSUE TITLE
How to track KL divergence and reconstruction loss separately during training?

### ISSUE THREAD

**Issue by dandanpeng** [matsengrp/vampire#122]
This may be a stupid question. But I cannot figure out how to extract KL divergence and reconstruction loss from the multiple outputs model? If it's a single output model, I think 'add_loss' can solve my question.

**Comment by krdav** [comment]
Hi Dandan,
Can you provide a bit of context? How are you running it using the scons workflow or directly working with the .py scripts? Some code showing what you mean would also be helpful.

**Comment by dandanpeng** [comment]
Hi Krdav, 
I wanted to edit the py. scripts and track the reconstruction error and KL divergence separately during training. Now I have solved it. This is basically a Keras related problem rather than Vampire-related. Anyway, thanks for the reply : )
