### ISSUE TITLE
yml file out of date / tensorflow docker? 

### ISSUE THREAD

**Issue by chenling-immunai** [matsengrp/vampire#124]
Hi,
I am trying to run vampire using the instructions in readme, and the first error I encountered was that tensorflow wasn't installed. After pip installing tensorflow and trying to run demo.sh, I got the warning that the GPU wasn't set up, and then the error that `from keras import objectives`failed. I suspect that it is because keras had updated, and the version is not specified in the yml file. It is alluded that you run your method on a tensorflow docker image? Could you send more details about that? 
Thank you! 
Best,
Chenling

**Comment by krdav** [comment]
Hello Chenling,

You are completely right, the keras version was left unspecified in the yml instructions so the newest version is installed per default and this is what causes your problem.
We are not actively developing, or using the code, in this project as you can probably see from the commit history. That being said, I just committed a change to the yml file to specific the keras version we were using back then and this seem to make the demo work again.

Best,
Kristian
